Repository infra-geo-ouverte/igo2-lib, pull requests merged in 2022-11, with the labels that each got.

#1116 fix(layer-list): follow checked or focused layer on layer displacement
  packages/geo/src/lib/layer/layer-list/layer-list.component.html
  packages/geo/src/lib/layer/layer-list/layer-list.component.ts
Labels: simple

#1065 feat(draw): Management of the editing of individual element
  package-lock.json
  package.json
  packages/common/src/lib/entity/entity-table/entity-table.component.html
  packages/common/src/lib/entity/entity-table/entity-table.component.ts
  packages/common/src/lib/entity/shared/entity.interfaces.ts
  packages/geo/package.json
  packages/geo/src/lib/draw/draw/draw-popup.component.html
  packages/geo/src/lib/draw/draw/draw-popup.component.ts
  packages/geo/src/lib/draw/draw/draw.component.html
  packages/geo/src/lib/draw/draw/draw.component.scss
  packages/geo/src/lib/draw/draw/draw.component.ts
  packages/geo/src/lib/draw/draw/draw.module.ts
  packages/geo/src/lib/draw/shared/draw-style.service.ts
  packages/geo/src/lib/draw/shared/draw.interface.ts
  packages/geo/src/lib/layer/index.ts
  packages/geo/src/lib/layer/layer.module.ts
  packages/geo/src/lib/layer/style-modal/index.ts
  packages/geo/src/lib/layer/style-modal/style-modal.component.html
  packages/geo/src/lib/layer/style-modal/style-modal.component.scss
  packages/geo/src/lib/layer/style-modal/style-modal.component.ts
  packages/geo/src/locale/en.geo.json
  packages/geo/src/locale/fr.geo.json
Labels: ready to merge

#1127 feat(edition): allow absolute url if config is not defined
  packages/geo/src/lib/workspace/shared/edition-workspace.service.ts
  packages/geo/src/lib/workspace/shared/edition-workspace.ts
Labels: ready to merge

#1129 fix(hover): fix flashing feature and property transfer
  demo/src/app/geo/hover/hover.component.ts
  packages/geo/src/lib/map/shared/hover-feature.directive.ts
Labels: to test

#1117 Rotation
  packages/geo/src/lib/map/rotation-button/rotation-button.component.html
  packages/geo/src/lib/map/rotation-button/rotation-button.component.ts
  packages/geo/src/lib/map/shared/controllers/view.ts
  packages/geo/src/lib/map/shared/map.ts
  packages/geo/src/locale/en.geo.json
  packages/geo/src/locale/fr.geo.json
Labels: to test, simple

#1081 feat(draw): Make multiple layers with the drawing tool
  demo/src/app/geo/draw/draw.component.html
  demo/src/app/geo/draw/draw.component.ts
  packages/common/src/lib/entity/entity-table/entity-table.component.html
  packages/geo/src/lib/draw/draw/draw-layer-popup.component.html
  packages/geo/src/lib/draw/draw/draw-layer-popup.component.scss
  packages/geo/src/lib/draw/draw/draw-layer-popup.component.ts
  packages/geo/src/lib/draw/draw/draw.component.html
  packages/geo/src/lib/draw/draw/draw.component.scss
  packages/geo/src/lib/draw/draw/draw.component.ts
  packages/geo/src/lib/draw/draw/draw.module.ts
  packages/geo/src/lib/draw/draw/draw.theming.scss
  packages/geo/src/lib/draw/shared/draw.interface.ts
  packages/geo/src/locale/en.geo.json
  packages/geo/src/locale/fr.geo.json
  packages/integration/src/lib/draw/draw.state.ts
  packages/integration/src/lib/draw/drawing-tool/drawing-tool.component.html
  packages/integration/src/lib/draw/drawing-tool/drawing-tool.component.ts
Labels: ready to merge

#1109 Layer profils
  packages/context/src/lib/context-manager/shared/context.service.ts
  packages/geo/src/lib/catalog/catalog-browser/catalog-browser.component.ts
  packages/geo/src/lib/catalog/shared/catalog.abstract.ts
  packages/geo/src/lib/layer/shared/layers/layer.interface.ts
Labels: to test, simple

#1092 feat(draw): Drawing coordinate label
  packages/common/src/lib/entity/entity-table/entity-table.component.scss
  packages/geo/src/lib/draw/draw/draw-popup.component.html
  packages/geo/src/lib/draw/draw/draw-popup.component.scss
  packages/geo/src/lib/draw/draw/draw-popup.component.ts
  packages/geo/src/lib/draw/draw/draw.component.html
  packages/geo/src/lib/draw/draw/draw.component.scss
  packages/geo/src/lib/draw/draw/draw.component.ts
  packages/geo/src/lib/draw/draw/draw.module.ts
  packages/geo/src/lib/draw/shared/draw-style.service.ts
  packages/geo/src/lib/draw/shared/draw.enum.ts
  packages/geo/src/lib/draw/shared/draw.interface.ts
  packages/geo/src/lib/draw/shared/draw.utils.ts
  packages/geo/src/lib/map/shared/map.utils.ts
  packages/geo/src/locale/en.geo.json
  packages/geo/src/locale/fr.geo.json
Labels: ready to merge
