Repository infra-geo-ouverte/igo2-lib, pull requests merged in 2022-10, with the labels that each got.

#1108 fix(*): delete geometry column from search result or query
  packages/geo/src/lib/query/shared/query.service.ts
  packages/geo/src/lib/search/shared/search.utils.ts
Labels: simple, ready to merge

#1091 feat(message) - add param noIcon display and add show message type from ngx-toaster
  packages/core/src/lib/message/message.theming.scss
  packages/core/src/lib/message/shared/message.enum.ts
  packages/core/src/lib/message/shared/message.interface.ts
  packages/core/src/lib/message/shared/message.service.ts
Labels: simple, ready to merge

#1085 feat(geolocate): add basic icon button config
  packages/geo/src/lib/map/geolocate-button/geolocate-button.component.html
  packages/geo/src/lib/map/geolocate-button/geolocate-button.component.ts
  packages/geo/src/locale/en.geo.json
  packages/geo/src/locale/fr.geo.json
Labels: simple

#1063 Message translation on language change
  packages/context/src/lib/context-manager/shared/context.service.ts
  packages/core/src/lib/language/shared/language.service.ts
  packages/core/src/lib/message/shared/message.interface.ts
  packages/core/src/lib/message/shared/message.service.ts
Labels: to test

#1095 feat(import-export) GUI add custom html for clarification
  packages/geo/src/lib/import-export/import-export.module.ts
  packages/geo/src/lib/import-export/import-export/import-export.component.html
  packages/geo/src/lib/import-export/import-export/import-export.component.ts
  packages/geo/src/locale/en.geo.json
  packages/geo/src/locale/fr.geo.json
Labels: simple

#1072 fix(arcgis): url remplacement may cause errors if mapserver is not enabled
  packages/geo/src/lib/datasource/shared/capabilities.service.ts
Labels: to test, simple

#1114 feat(feature-details): copy content button alongside the url
  packages/geo/src/lib/feature/feature-details/feature-details.component.html
  packages/geo/src/lib/feature/feature-details/feature-details.component.scss
  packages/geo/src/lib/feature/feature-details/feature-details.component.ts
  packages/geo/src/locale/en.geo.json
  packages/geo/src/locale/fr.geo.json
Labels: simple
