Repository infra-geo-ouverte/igo2-lib, pull requests merged in 2023-04, with the labels that each got.

#1212 fix(geo): export map and legend in the same file zip
  packages/geo/src/lib/print/print/print.component.ts
  packages/geo/src/lib/print/shared/print.service.ts
Labels: bug

#1215 fix(geo): add attribution and copyright if export pdf or image
  packages/geo/src/lib/print/shared/print.service.ts
Labels: bug, enhancement

#1222 fix(geo, integration): solve config bug save search result in layer
  packages/geo/src/lib/search/search-results/search-results-add-button.component.html
  packages/geo/src/lib/search/search-results/search-results-add-button.component.ts
  packages/integration/src/lib/search/search-results-tool/search-results-tool.component.html
Labels: bug

#1150 14lts
  .github/workflows/codeql-analysis.yml
  .github/workflows/complete.js.yml
  .github/workflows/gh-release.yml
  .github/workflows/onPush-ci.js.yml
  README.md
  demo/src/styles.scss
  package-lock.json
  package.json
  packages/auth/package.json
  packages/common/package.json
  packages/context/package.json
  packages/core/package.json
  packages/geo/package.json
  packages/integration/package.json
  packages/utils/package.json
Labels: wait for 1.15
