Repository infra-geo-ouverte/igo2-lib, pull requests merged in 2023-06, with the labels that each got.

#1256 feat(geo): Added rotate option and north direction to the map when pr…
  packages/geo/src/lib/print/shared/print.service.ts
Labels: enhancement, in progress

#1299 Feat vscode debugging
  .vscode/launch.json
  .vscode/tasks.json
Labels: enhancement

#1300 fix(integration): import Action interface and add DatePipe in domo app.module to solve datepipe issue
  demo/src/app/app.module.ts
  packages/integration/src/lib/workspace/shared/workspace.utils.ts
Labels: bug

#1301 Fix printing multi canvas of victor layers
  packages/geo/src/lib/print/shared/print.service.ts
Labels: bug
