Repository infra-geo-ouverte/igo2-lib, pull requests merged in 2023-01, with the labels that each got.

#1148 perf(integration): add click action on igo-panel-title to show location details
  packages/common/src/lib/panel/panel.component.html
  packages/common/src/lib/panel/panel.component.scss
  packages/common/src/lib/panel/panel.component.ts
  packages/integration/src/lib/search/search-results-tool/search-results-tool.component.html
  packages/integration/src/lib/search/search-results-tool/search-results-tool.component.ts
Labels: enhancement, ready to merge

#1157 Search - Remove the number of results #829
  packages/geo/src/lib/search/search-results/search-results.component.ts
Labels: ready to merge

#1158 ui(search-bar): Invert reset button and search button
  packages/geo/src/lib/search/search-bar/search-bar.component.html
Labels: ready to merge

#1161 Fix(draw.component) button zoomToExtent on draw layer
  packages/geo/src/lib/draw/draw/draw.component.ts
Labels: ready to merge

#1163 feat(icherche): ajout des haltes cyclables et routières
  packages/geo/src/lib/search/shared/sources/icherche.ts
  packages/geo/src/locale/en.geo.json
  packages/geo/src/locale/fr.geo.json
Labels: ready to merge

#1164 refactor(search-bar): switched from input to config for search button
  packages/geo/src/lib/search/search-bar/search-bar.component.html
  packages/geo/src/lib/search/search-bar/search-bar.component.ts
Labels: ready to merge

#1171 fix(search-result): allow more results on a filtered state
  packages/geo/src/lib/search/search-results/search-results.component.ts
Labels: to test
