Repository infra-geo-ouverte/igo2-lib, pull requests merged in 2023-03, with the labels that each got.

#1125 feat(regexService): config define regex list/object
  packages/core/src/lib/regex/index.ts
  packages/core/src/lib/regex/regex.interface.ts
  packages/core/src/lib/regex/regex.service.ts
  packages/core/src/public_api.ts
Labels: to test, simple

#1189 fix(search-source): fix language reload on search source
  packages/core/src/lib/language/shared/language.service.ts
  packages/geo/src/lib/search/shared/sources/coordinates.ts
  packages/geo/src/lib/search/shared/sources/icherche.ts
  packages/geo/src/lib/search/shared/sources/ilayer.ts
Labels: ready to merge, 1.14.2

#1184 feat(ilayer/catalog): add visible/non-visible badge icon
  packages/common/src/lib/badge-icon/badge-icon.directive.ts
  packages/geo/src/lib/catalog/catalog-browser/catalog-browser-group.component.html
  packages/geo/src/lib/catalog/catalog-browser/catalog-browser-group.component.ts
  packages/geo/src/lib/catalog/catalog-browser/catalog-browser-layer.component.html
  packages/geo/src/lib/catalog/catalog-browser/catalog-browser-layer.component.ts
  packages/geo/src/lib/catalog/catalog-browser/catalog-browser.component.html
  packages/geo/src/lib/search/search-results/search-results-add-button.component.html
  packages/geo/src/lib/search/search-results/search-results-add-button.component.ts
  packages/geo/src/locale/en.geo.json
  packages/geo/src/locale/fr.geo.json
Labels: ready to merge, 1.14.2

#1167 feat(geo): update queryUrl with min max resolution
  demo/src/app/geo/query/query.component.ts
  packages/geo/src/lib/query/shared/query.interfaces.ts
  packages/geo/src/lib/query/shared/query.service.ts
Labels: enhancement, ready to merge, 1.14.2

#1191 fix(geo): solve absence of legend when printing an image
  demo/src/locale/en.json
  demo/src/locale/fr.json
  packages/geo/src/lib/print/print-form/print-form.component.html
  packages/geo/src/lib/print/print/print.component.ts
  packages/geo/src/lib/print/shared/print.service.ts
  packages/geo/src/locale/en.geo.json
  packages/geo/src/locale/fr.geo.json
Labels: bug, ready to merge, 1.14.2

#1179 feat(geo): save search results in layer
  packages/geo/src/lib/search/search-results/save-feature-dialog.component.html
  packages/geo/src/lib/search/search-results/save-feature-dialog.component.scss
  packages/geo/src/lib/search/search-results/save-feature-dialog.component.ts
  packages/geo/src/lib/search/search-results/search-results-add-button.component.html
  packages/geo/src/lib/search/search-results/search-results-add-button.component.ts
  packages/geo/src/lib/search/search-results/search-results.component.ts
  packages/geo/src/lib/search/search-results/search-results.module.ts
  packages/geo/src/locale/en.geo.json
  packages/geo/src/locale/fr.geo.json
  packages/integration/src/lib/draw/draw.state.ts
  packages/integration/src/lib/search/search-results-tool/search-results-tool.component.html
  packages/integration/src/lib/search/search-results-tool/search-results-tool.component.ts
Labels: enhancement, ready to merge, 1.14.2

#1174 chore(*): RIP Internet Explorer
  .browserslistrc
  demo/src/.browserslistrc
  demo/src/app/app.component.ts
  packages/geo/src/lib/feature/feature-details/feature-details.component.ts
  packages/geo/src/lib/overlay/shared/overlay-marker-style.utils.ts
  packages/geo/src/lib/print/shared/print.service.ts
  packages/geo/src/lib/search/shared/search-pointer-summary.directive.ts
Labels: to test, wait for 1.15

#1156 perf(geo): changer l'affichage de Query du liste collapse ver afficha…
  packages/geo/src/lib/search/search-results/search-results.component.html
  packages/geo/src/lib/search/search-results/search-results.component.scss
  packages/geo/src/lib/search/search-results/search-results.component.ts
  packages/geo/src/lib/search/search-results/search-results.module.ts
Labels: ready to merge, 1.14.2

#1187 chore(*): upgrade to ol 7.3.0
  package-lock.json
  package.json
  packages/context/package.json
  packages/geo/package.json
Labels: wait for 1.15

#1206 feat(integration): Make the save search result option configurable
  packages/geo/src/lib/feature/shared/strategies/search.ts
  packages/geo/src/lib/search/search-results/save-feature-dialog.component.html
  packages/geo/src/lib/search/search-results/save-feature-dialog.component.ts
  packages/geo/src/lib/search/search-results/search-results-add-button.component.ts
  packages/integration/src/lib/search/search-results-tool/search-results-tool.component.html
  packages/integration/src/lib/search/search-results-tool/search-results-tool.component.ts
Labels: enhancement, in progress
