Repository infra-geo-ouverte/igo2-lib, pull requests merged in 2024-02, with the labels that each got.

#1626 feat(geo): change printed text to Sans Serif font
  packages/geo/src/lib/print/shared/print.service.ts
Labels: enhancement

#1570 fix(geo): check Capability contains layers list before loop
  packages/geo/src/lib/catalog/shared/catalog.service.ts
Labels: bug, ready to merge

#1608 fix(geo): garantine no comma in the beginning and end of search term
  packages/geo/src/lib/search/shared/sources/cadastre.ts
Labels: bug, ready to merge

#1633 1632 la modale dauthentification le bouton se connecter et rester anonyme
  packages/auth/ng-package.json
  packages/auth/ng-package.prod.json
  packages/auth/src/auth.theme.scss
  packages/auth/src/lib/auth-form/auth-intern.component.html
  packages/auth/src/lib/auth-form/auth-intern.component.scss
  packages/auth/src/lib/auth-form/auth-intern.theme.scss
  packages/auth/src/lib/auth.module.ts
  packages/auth/src/locale/fr.auth.json
  packages/core/src/packages.import.scss
  packages/core/src/theming/all-theme.scss
Labels: ready to merge

#1620 fix(integration): fix advanced coordinate error Maximum call stack si…
  packages/integration/src/lib/map/advanced-map-tool/advanced-coordinates/advanced-coordinates.component.ts
Labels: bug, ready to merge
