Repository infra-geo-ouverte/igo2-lib, pull requests merged in 2024-05, with the labels that each got.

#1622 fix(geo): ensure ogc filter accept today and now
  packages/geo/src/lib/filter/ogc-filter-time/ogc-filter-time.component.ts
  packages/geo/src/lib/filter/shared/ogc-filter.ts
Labels: bug, ready to merge

#1654 feat(integration, common, geo): keep selected catalog when changing tools
  packages/common/src/lib/tool/shared/toolbox.ts
  packages/geo/src/lib/catalog/catalog-library/catalog-library.component.ts
  packages/integration/src/lib/catalog/catalog-library-tool/catalog-library-tool.component.ts
Labels: enhancement, ready to merge

#1660 fix(context): add workspace option with layers when we export context
  packages/context/src/lib/context-manager/shared/context.service.ts
Labels: bug, ready to merge

#1661 fix(integration): update latitude and longitude if coords system change
  packages/integration/src/lib/map/advanced-map-tool/advanced-coordinates/advanced-coordinates.component.ts
Labels: bug, ready to merge

#1662 fix(geo): Print set the same horizontal margin for the map
  packages/geo/src/lib/directions/shared/directions.service.ts
  packages/geo/src/lib/print/shared/print.service.ts
Labels: bug, ready to merge

#1665 fix(geo): import and export shp file
  packages/geo/src/lib/import-export/shared/export.service.ts
  packages/geo/src/lib/style/shared/feature/feature-style.ts
  packages/utils/src/lib/file.ts
Labels: bug, ready to merge

#1670 feat(geo): print - add map attribution under the map
  packages/geo/src/lib/directions/shared/directions.service.ts
  packages/geo/src/lib/print/shared/print.service.ts
Labels: enhancement, ready to merge

#1672 feat(geo): print add option to show hide north arrow direction
  packages/geo/src/assets/images/north-direction.png
  packages/geo/src/lib/print/print-form/print-form.component.html
  packages/geo/src/lib/print/print-form/print-form.component.ts
  packages/geo/src/lib/print/print/print.component.ts
  packages/geo/src/lib/print/shared/print.interface.ts
  packages/geo/src/lib/print/shared/print.service.ts
  packages/geo/src/locale/en.geo.json
  packages/geo/src/locale/fr.geo.json
Labels: enhancement, ready to merge

#1683 feat: automate the release and publishing with semantic-release
  .github/workflows/gh-release.yml
  .github/workflows/onPush-ci.js.yml
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
  .madgerc
  package-lock.json
  package.json
  packages/auth/package.json
  packages/common/package.json
  packages/context/package.json
  packages/core/package.json
  packages/geo/package.json
  packages/integration/package.json
  packages/utils/package.json
  projects/demo/package.json
  scripts/src/build-library.mts
  scripts/src/build-library.ts
  scripts/src/common/postbuild-common.mts
  scripts/src/config/packages.mts
  scripts/src/config/paths.mts
  scripts/src/config/release.interface.mts
  scripts/src/core/clean-exports.ts
  scripts/src/core/postbuild-core.mts
  scripts/src/core/prestart-core.mts
  scripts/src/core/utils/assets.mts
  scripts/src/core/utils/localization.mts
  scripts/src/core/utils/version.utils.mts
  scripts/src/geo/postbuild-geo.mts
  scripts/src/postbuild-library.mts
  scripts/src/pre-release.mts
  scripts/src/publish.mts
  scripts/src/release-demo.mts
  scripts/src/release.mts
  scripts/src/release/github-pages.ts
  scripts/src/release/release.interface.ts
  scripts/src/release/release.ts
  scripts/src/utils/color.mts
  scripts/src/utils/executor.mts
  scripts/src/utils/file-system.utils.mts
  scripts/src/utils/log.mts
  scripts/src/utils/performance.utils.mts
  scripts/src/utils/style.utils.mts
  scripts/tsconfig.json
Labels: enhancement
